version: '3'
services: 
  db:
    container_name: bdcomercio
    image: mariadb
    environment:
      MARIADB_USER: comercio
      MARIADB_PASSWORD: pswcomercio
      MARIADB_DATABASE: comercio
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3310:3306"
